# Generated by Django 4.1.1 on 2022-09-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
