# Generated by Django 4.1.1 on 2022-09-12 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_card_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='url',
            new_name='link',
        ),
    ]
